# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c103074bd07d620e9f2bb0840129ec59e3c82428aa4a86646f14fee43e1a0866d8271eaab6b2c1fba3f563713f9cea481490127d3e9c3e9a4e87874809175a61

test:
  secret_key_base: 8df3ab7bbe6bac9cf9487a87e485898f38223e93c2876890db62b2f6f80c449ed47a3dc6a789ff77d757cdeb9ea000621680c110e09c62ff1389f7f4444eccd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
